function [ecceAnomaly_t] = newtonSimpson(eccentricity,meanAnomaly)
%牛顿辛普森迭代法求解偏近点角
ecceAnomaly     = meanAnomaly;
ecceAnomaly_t   = ecceAnomaly - ...
    (ecceAnomaly - eccentricity*sin(ecceAnomaly) - meanAnomaly)/...
    (1 - eccentricity*cos(ecceAnomaly));
while abs(ecceAnomaly_t-ecceAnomaly) >= 1e-8 ||...
        (ecceAnomaly_t - eccentricity*sin(ecceAnomaly_t) - meanAnomaly) >= 1e-8
    ecceAnomaly = ecceAnomaly_t;
    ecceAnomaly_t = ecceAnomaly - ...
        (ecceAnomaly - eccentricity*sin(ecceAnomaly) - meanAnomaly)/...
        (1 - eccentricity*cos(ecceAnomaly));
end
end